version: '2.17.3'

services:
  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    restart: always
  main:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis

# Refer to super important comment in store_service.go or refer to this:
# https://stackoverflow.com/questions/42360356/docker-redis-connection-refused

